tokens = {'CREATE':'tk_crear',
        'SET':'tk_espacio_memoria',
        'PALABRA':'tk_palabra',
        'NUMERO':'tk_numero',
        'LOAD':'tk_leer',
        'INTO':'tk_dentro_de',
        'FILES':'tk_archivos',
        'USE':'tk_usar',
        ',':'tk_coma',
        'WHERE':'tk_donde',
        '=':'tk_igual',
        'AND':'tk_and',
        'OR':'tk_or',
        'XOR':'tk_xor',
        '<':'tk_menor_que',
        '>':'tk_mayor_que',
        '<=':'tk_menor_igual',
        '>=':'tk_mayor_igual',
        '!=':'tk_noigual',
        'SELECT':'tk_seleccionar',
        'LIST':'tk_lista',
        'ATTRIBUTES':'tk_attributos',
        'PRINT':'tk_imprimir',
        'IN':'tk_en',
        'MAX':'tk_maximo',
        'MIN':'tk_minimo',
        'SUM':'tk_suma',
        'COUNT':'tk_contar',
        'REPORT':'tk_reporte',
        'TO':'tk_doreccion',
        'SCRIPT':'tk_sript',
        'TOKENS':'tk_definicion_token',
        'REGEX':'tk_regular_exp',
        '^':'tk_primer_elemento',
        '|':'tk_opcion',
        '.':'tk_cualquier_caracter',
        '+':'tk_una_muchas',
        '*':'tk_cero_muchas',
        '?':'tk_cero_uno',
        '(':'tk_inicio_agrupacion',
        ')':'tk_fin_agrupacion',
        '[':'tk_inicio_limite',
        ']':'tk_fin_limite',
        ';':'tk_punto_y_coma',
        'BLUE':'tk_azul',
        'RED':'tk_rojo',
        'GREEN':'tk_verde',
        'YELLOW':'tk_amarillo',
        'ORANGE':'tk_naranja',
        'PINK':'tk_rosa',

}

definicion_token = {'CREATE':'Insctruccion que ordena la creacion de algo',
        'SET':'Es un espacio en memoria, reservada con un nombre',
        'PALABRA':'Es un identificador, agrupacion de caracteres',
        'NUMERO':'Es un valor numerico',
        'LOAD':'Comando Cargar',
        'INTO':'hace referencia a algo',
        'FILES':'Archivo, especifica que lo que se tiene  despues de esta instruccion es un archivo',
        'USE':'define que elemento de memoria se utilizara',
        ',':'denota fin de algo para dar comienzo a otro elemento',
        'WHERE':'define el inicio de una o mas condiciones',
        '=':'describe que algo debe ser igual',
        'AND':'indica que la sigueiente condicion tambien debe cumplirse',
        'OR':'indica que la siguiente condicion puede o no cumplirse',
        'XOR':'indica que una de las dos condiciones debe cumplirse',
        '<':'indica que el atriburo debe ser menor que',
        '>':'indica que el atributo debe ser mayor que',
        '<=':'indica que el atributo debe ser menor o igual que',
        '>=':'indica que el atributo debe ser mayor o igual que',
        '!=':'indica que el atributo no debe ser igual que',
        'SELECT':'comando para seleccionar algo',
        'LIST':'comando que describe una lista',
        'ATTRIBUTES':'retorna los atributos de un set de memoria',
        'PRINT':'comando utilizado para cambiar las propiedades de consola ',
        'IN':'hace referencia a un color',
        'MAX':'retonra el valor maximo de un atributo',
        'MIN':'retonra el valor minimo de un atributo',
        'SUM':'retorna la suma de todos los valores de un atributo',
        'COUNT':'retorna la cuenta de todos los elementos de un atributo en sepecifico',
        'REPORT':'genera un reporte del tipo que se especifica posteriormente  ',
        'TO':'hace referencia a otro comando',
        'SCRIPT':'se carga un script con instrucciones',
        'TOKENS':'define el listado de tokens en el script',
        'REGEX':'hace referencia a una o varias condiciones',
        '^':'Se utiliza para definir cuál será el primer elemento en la cadena',
        '|':'Se utiliza para separar opciones, es decir que en una cadena pueda venir el elemento a la izquierda o el elemento a laderecha',
        '.':'denota cualquier caracter',
        '+':'Define que el elemento anterior puede venir entre una y muchas veces',
        '*':'Define que el elemento anterior puede venir desde cero a muchas veces',
        '?':'Define que el elemento anterior puede venir una vez o no venir',
        '(':'inicio de agrupacion de elementos tomandolos como uno solo',
        ')':'fin de agrupacion de elementos tomandolos como uno solo',
        '[':'inicio de los caracteres que rodean a la regex para delimitarla',
        ']':'fin de los caracteres que rodean a la regex para delimitarla',
        ';':'denota el fin de un comando en siql',
        'BLUE':'El color en consala sera azul',
        'RED':'El color en consala sera rojo',
        'GREEN':'El color en consala sera verde',
        'YELLOW':'El color en consala sera amarillo',
        'ORANGE':'El color en consala sera naranja',
        'PINK':'El color en consala sera rosa'
}